# Generated by Django 2.2 on 2020-06-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name=''),
            preserve_default=False,
        ),
    ]
